### ISSUE TITLE
Text size on Win 8 for preferences window

### ISSUE THREAD

**Issue by Eneroth3** [SketchUp/testup-2#99]
![win 8 scaling](https://user-images.githubusercontent.com/5631725/34070916-eecd77c4-e26d-11e7-9c13-ff4c4fce22f3.png)

On Win 8 with DPI scaling set to 125% text sizing and scaling of other elements seem to be out of sync. If I am not mistaking the text alone is scaled but not the other elements. This applies to the preferences window but not the main window.

**Comment by Aerilius** [comment]
That looks nice! It's even more extreme with 200%.

**Comment by Aerilius** [comment]
For reference: https://github.com/thomthom/SKUI/issues/107

I have to test again because on a different system, it is displayed correctly at 200% (which modern browsers should do automatically). It seems under some conditions (version, doctype?), IE scales the fonts by an extra factor in addition to scaling everything consistently.

**Comment by thomthom** [comment]
Yes, this is an issue coming from SKUI. I wonder if I have a patch I never submitted. I'll have to dig around.
I've been using my Retina monitor more recently (200% scale) and I see this issue even worse.
